import { sidebarMenuType } from "Types/LayoutDataType";

export const MenuList: sidebarMenuType[] = [
  {
    title: "Dashboard",
    menucontent: "Dashboard",
    Items: [
      {
        title: "Dashboard",
        id: 1,
        icon: "home",
        path: "/dashboard",
        type: "link",
      },
    ],
  },
  {
    title: "İçerik Yönetimi",
    menucontent: "İçerik Yönetimi",
    Items: [
      {
        title: "Projeler",
        id: 2,
        icon: "briefcase",
        type: "sub",
        pathSlice: "projects",
        moduleKey: "projects",
        children: [
          {
            title: "Tüm Projeler",
            type: "link",
            path: "/admin/projects",
            pathSlice: "projects",
            moduleKey: "projects",
          },
          {
            title: "Yeni Proje Ekle",
            type: "link",
            path: "/admin/projects/create",
            pathSlice: "projects",
            moduleKey: "projects",
          },
        ],
      },
      {
        title: "Haber Yönetimi",
        id: 6,
        icon: "file-text",
        type: "link",
        path: "/admin/news",
        pathSlice: "news",
        moduleKey: "news",
      },
      {
        title: "Galeri",
        id: 8,
        icon: "image",
        type: "link",
        path: "/admin/gallery",
        pathSlice: "gallery",
        moduleKey: "gallery",
      },
      {
        title: "Tarihçe",
        id: 14,
        icon: "calendar",
        type: "link",
        path: "/admin/timeline",
        pathSlice: "timeline",
        moduleKey: "timeline",
      },
      {
        title: "Ekip Üyeleri",
        id: 15,
        icon: "users",
        type: "link",
        path: "/admin/team-members",
        pathSlice: "team-members",
        moduleKey: "team-members",
      },
    ],
  },
  {
    title: "Bağış Yönetimi",
    menucontent: "Bağış Yönetimi",
    Items: [
      {
        title: "Kampanyalar",
        id: 7,
        icon: "target",
        type: "sub",
        pathSlice: "campaigns",
        moduleKey: "campaigns",
        children: [
          {
            title: "Tüm Kampanyalar",
            type: "link",
            path: "/admin/campaigns",
            pathSlice: "campaigns",
            moduleKey: "campaigns",
          },
          {
            title: "Yeni Kampanya",
            type: "link",
            path: "/admin/campaigns/create",
            pathSlice: "campaigns",
            moduleKey: "campaigns",
          },
          {
            title: "Kampanya Ayarları",
            type: "link",
            path: "/admin/campaign-settings",
            pathSlice: "campaign-settings",
            moduleKey: "campaign-settings",
          },
        ],
      },
      {
        title: "Bağışlar",
        id: 16,
        icon: "heart",
        type: "sub",
        pathSlice: "donations",
        moduleKey: "donations",
        children: [
          {
            title: "Tüm Bağışlar",
            type: "link",
            path: "/admin/donations",
            pathSlice: "donations-list",
            moduleKey: "donations-list",
          },
          {
            title: "Düzenli Bağışlar",
            type: "link",
            path: "/admin/recurring-donations",
            pathSlice: "recurring-donations",
            moduleKey: "recurring-donations",
          },
          {
            title: "Ödeme İşlemleri",
            type: "link",
            path: "/admin/payment-transactions",
            pathSlice: "payment-transactions",
            moduleKey: "payment-transactions",
          },
        ],
      },
      {
        title: "Banka Hesapları",
        id: 17,
        icon: "dollar-sign",
        type: "link",
        path: "/admin/bank-accounts",
        pathSlice: "bank-accounts",
        moduleKey: "bank-accounts",
      },
    ],
  },
  {
    title: "Başvuru Yönetimi",
    menucontent: "Başvuru Yönetimi",
    Items: [
      {
        title: "İletişim Mesajları",
        id: 11,
        icon: "mail",
        type: "link",
        path: "/admin/contact",
        pathSlice: "contact",
        moduleKey: "contact",
      },
      {
        title: "Gönüllü Başvuruları",
        id: 9,
        icon: "user-check",
        type: "link",
        path: "/admin/volunteers",
        pathSlice: "volunteers",
        moduleKey: "volunteers",
      },
      {
        title: "Kariyer Başvuruları",
        id: 10,
        icon: "briefcase",
        type: "link",
        path: "/admin/careers",
        pathSlice: "careers",
        moduleKey: "careers",
      },
    ],
  },
  {
    title: "Sistem",
    menucontent: "Sistem",
    Items: [
      {
        title: "Kullanıcılar",
        id: 3,
        icon: "users",
        type: "sub",
        pathSlice: "users",
        moduleKey: "users",
        children: [
          {
            title: "Tüm Kullanıcılar",
            type: "link",
            path: "/admin/users",
            pathSlice: "users",
            moduleKey: "users",
          },
          {
            title: "Yeni Kullanıcı",
            type: "link",
            path: "/admin/users/create",
            pathSlice: "users",
            moduleKey: "users",
          },
        ],
      },
      {
        title: "Roller & İzinler",
        id: 4,
        icon: "shield",
        type: "sub",
        pathSlice: "authorization",
        moduleKey: "roles",
        children: [
          {
            title: "Roller",
            type: "link",
            path: "/admin/roles",
            pathSlice: "roles",
            moduleKey: "roles",
          },
          {
            title: "Yeni Rol",
            type: "link",
            path: "/admin/roles/create",
            pathSlice: "roles",
            moduleKey: "roles",
          },
        ],
      },
      {
        title: "Modül Yönetimi",
        id: 12,
        icon: "layers",
        type: "link",
        path: "/admin/modules",
        pathSlice: "modules",
        moduleKey: "modules",
      },
      {
        title: "Sistem Ayarları",
        id: 13,
        icon: "settings",
        type: "link",
        path: "/admin/system-settings",
        pathSlice: "system-settings",
        moduleKey: "settings",
      },
    ],
  },
];
