import { sidebarMenuType } from "Types/LayoutDataType";

export const MenuList: sidebarMenuType[] = [
  {
    title: "Ana Menü",
    menucontent: "Dashboard",
    Items: [
      {
        title: "Dashboard",
        id: 1,
        icon: "home",
        path: "/dashboard",
        type: "link",
      },
    ],
  },
  {
    title: "Yönetim",
    menucontent: "Sistem Yönetimi",
    Items: [
      {
        title: "Projeler",
        id: 2,
        icon: "briefcase",
        type: "sub",
        pathSlice: "projects",
        moduleKey: "projects",
        children: [
          {
            title: "Tüm Projeler",
            type: "link",
            path: "/admin/projects",
            pathSlice: "projects",
            moduleKey: "projects",
          },
          {
            title: "Yeni Proje Ekle",
            type: "link",
            path: "/admin/projects/create",
            pathSlice: "projects",
            moduleKey: "projects",
          },
          {
            title: "Kategoriler",
            type: "link",
            path: "/admin/projects/categories",
            pathSlice: "projects",
            moduleKey: "projects",
          },
          {
            title: "Arşiv",
            type: "link",
            path: "/admin/projects/archive",
            pathSlice: "projects",
            moduleKey: "projects",
          },
        ],
      },
      {
        title: "Kullanıcı Yönetimi",
        id: 3,
        icon: "users",
        type: "sub",
        pathSlice: "users",
        moduleKey: "users",
        children: [
          {
            title: "Tüm Kullanıcılar",
            type: "link",
            path: "/admin/users",
            pathSlice: "users",
            moduleKey: "users",
          },
          {
            title: "Yeni Kullanıcı Ekle",
            type: "link",
            path: "/admin/users/create",
            pathSlice: "users",
            moduleKey: "users",
          },
          {
            title: "Aktivite Logları",
            type: "link",
            path: "/admin/users/activity",
            pathSlice: "users",
            moduleKey: "users",
          },
        ],
      },
      {
        title: "Yetkilendirme",
        id: 4,
        icon: "shield",
        type: "sub",
        pathSlice: "authorization",
        moduleKey: "roles",
        children: [
          {
            title: "Roller",
            type: "link",
            path: "/admin/roles",
            pathSlice: "roles",
            moduleKey: "roles",
          },
          {
            title: "Yeni Rol Ekle",
            type: "link",
            path: "/admin/roles/create",
            pathSlice: "roles",
            moduleKey: "roles",
          },
          {
            title: "İzinler",
            type: "link",
            path: "/admin/roles/permissions",
            pathSlice: "roles",
            moduleKey: "roles",
          },
        ],
      },
      {
        title: "Haber Yönetimi",
        id: 6,
        icon: "file-text",
        type: "link",
        path: "/admin/news",
        pathSlice: "news",
        moduleKey: "news",
      },
      {
        title: "Bağış Yönetimi",
        id: 7,
        icon: "heart",
        type: "sub",
        pathSlice: "donations",
        moduleKey: "donations",
        children: [
          {
            title: "Bağış Kampanyaları",
            type: "link",
            path: "/admin/campaigns",
            pathSlice: "campaigns",
            moduleKey: "campaigns",
          },
          {
            title: "Yeni Kampanya Ekle",
            type: "link",
            path: "/admin/campaigns/create",
            pathSlice: "campaigns",
            moduleKey: "campaigns",
          },
          {
            title: "Kampanya Ayarları",
            type: "link",
            path: "/admin/campaign-settings",
            pathSlice: "campaign-settings",
            moduleKey: "campaign-settings",
          },
          {
            title: "Tüm Bağışlar",
            type: "link",
            path: "/admin/donations",
            pathSlice: "donations-list",
            moduleKey: "donations-list",
          },
          {
            title: "Düzenli Bağışlar",
            type: "link",
            path: "/admin/recurring-donations",
            pathSlice: "recurring-donations",
            moduleKey: "recurring-donations",
          },
          {
            title: "Ödeme İşlemleri",
            type: "link",
            path: "/admin/payment-transactions",
            pathSlice: "payment-transactions",
            moduleKey: "payment-transactions",
          },
          {
            title: "Banka Hesapları",
            type: "link",
            path: "/admin/bank-accounts",
            pathSlice: "bank-accounts",
            moduleKey: "bank-accounts",
          },
        ],
      },
      {
        title: "Galeri Yönetimi",
        id: 8,
        icon: "image",
        type: "link",
        path: "/admin/gallery",
        pathSlice: "gallery",
        moduleKey: "gallery",
      },
      {
        title: "Gönüllü Başvuruları",
        id: 9,
        icon: "user-check",
        type: "link",
        path: "/admin/volunteers",
        pathSlice: "volunteers",
        moduleKey: "volunteers",
      },
      {
        title: "Kariyer Başvuruları",
        id: 10,
        icon: "briefcase",
        type: "link",
        path: "/admin/careers",
        pathSlice: "careers",
        moduleKey: "careers",
      },
      {
        title: "İletişim Mesajları",
        id: 11,
        icon: "mail",
        type: "link",
        path: "/admin/contact",
        pathSlice: "contact",
        moduleKey: "contact",
      },
      {
        title: "Modül Yönetimi",
        id: 12,
        icon: "layers",
        type: "sub",
        pathSlice: "modules",
        moduleKey: "modules",
        children: [
          {
            title: "Tüm Modüller",
            type: "link",
            path: "/admin/modules",
            pathSlice: "modules",
            moduleKey: "modules",
          },
          {
            title: "Yeni Modül Ekle",
            type: "link",
            path: "/admin/modules/create",
            pathSlice: "modules",
            moduleKey: "modules",
          },
        ],
      },
      {
        title: "Sistem Ayarları",
        id: 13,
        icon: "settings",
        type: "link",
        path: "/admin/system-settings",
        pathSlice: "system-settings",
        moduleKey: "settings",
      },
    ],
  },
];
